sonar.organization=vbenevides
sonar.projectKey=VBenevides_Glyphflow
sonar.sources=.
sonar.go.coverage.reportPaths=backend/coverage.out
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.exclusions=\
**/node_modules/**,\
**/dist/**,\
**/build/**,\
**/vendor/**,\
**/coverage/**
