version: '3'

tasks:
  build:
    cmds:
      - version="$(tr -d '[:space:]' < ../VERSION)" && GOOS={{.GOOS | default OS}} GOARCH={{.GOARCH | default "amd64"}} go build -tags "workerui{{if .EXTRA_TAGS}},{{.EXTRA_TAGS}}{{end}}" -trimpath -ldflags="-s -w -X github.com/VBenevides/Glyphflow/backend.Version=$version" -o "{{.OUTPUT | default "bin/glyphflow-worker"}}" ./cmd/worker
