import { useState, type FormEvent } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useAuth } from './auth'
import { api, type Page, type Resource } from './api'
import { DangerousAction } from './actions'
import { Button, DataTable, EmptyState, Input, PageHeader, Pagination, StatusPill } from './components'
import { QueryState } from './query'
import { hasPermission } from './permissions'
import { formatDateTime } from './format'

export function resourceState(resource: Resource) { return resource.enabled === false ? 'disabled' : resource.holder ? 'leased' : 'available' }

export function ResourceInventoryPage() {
  const { permissions } = useAuth(); const [page, setPage] = useState(1); const [creating, setCreating] = useState(false); const [draft, setDraft] = useState({ name: '', kind: 'exclusive' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const query = useQuery({ queryKey: ['resources', page], queryFn: ({ signal }) => api.get<Page<Resource>>('/api/v1/resources', { page, limit: 50 }, signal) }); const manage = hasPermission(permissions, 'resources.manage')
  const create = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await api.post('/api/v1/resources', { name: draft.name.trim(), kind: draft.kind }); setDraft({ name: '', kind: 'exclusive' }); setCreating(false); await query.refetch() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Resource creation failed') } finally { setBusy(false) } }
  return <main className="gf-content"><PageHeader title="Resources and leases" description="Exclusive resources, fencing counters, and active holders." action={manage && <Button onClick={() => { setCreating(true); setError('') }}>Create resource</Button>} />{creating && <section className="gf-card-panel"><h2>Create resource</h2><form className="gf-editor-form" onSubmit={create}><label>Name<Input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} required /></label><label>Kind<select className="gf-input" value={draft.kind} onChange={(event) => setDraft({ ...draft, kind: event.target.value })}><option value="exclusive">Exclusive</option></select></label>{error && <p className="gf-form-error" role="alert">{error}</p>}<div className="gf-dialog-actions"><Button type="button" variant="secondary" onClick={() => setCreating(false)}>Cancel</Button><Button type="submit" busy={busy}>Create resource</Button></div></form></section>}<QueryState query={query} empty="Create an exclusive resource for task placement.">{(data) => data.items.length ? <><DataTable caption="Resources" rows={data.items} columns={[{ key: 'name', label: 'Resource', render: (resource) => <Link to={`/resources/${resource.id}`}>{resource.name}</Link> }, { key: 'enabled', label: 'State', render: (resource) => <StatusPill status={resourceState(resource)} /> }, { key: 'holder', label: 'Holder', render: (resource) => resource.holder ? <Link to={`/runs/${resource.holder}`}>{resource.holder}</Link> : '—' }, { key: 'expiresAt', label: 'Lease expiry', className: 'gf-cell-nowrap', render: (resource) => <time dateTime={resource.expiresAt}>{formatDateTime(resource.expiresAt)}</time> }, { key: 'fencingToken', label: 'Fencing token' }, { key: 'actions', label: 'Actions', render: (resource) => manage && <DangerousAction label="Delete" onConfirm={() => api.delete(`/api/v1/resources/${encodeURIComponent(resource.id)}`).then(() => { void query.refetch() })} /> }]} /><Pagination page={data.page ?? page} pages={data.pages ?? 1} onChange={setPage} /></> : <EmptyState title="No resources">Create an exclusive resource for task placement.</EmptyState>}</QueryState></main>
}

export function ResourceDetailPage() {
  const { resourceId = '' } = useParams(); const navigate = useNavigate(); const query = useQuery({ queryKey: ['resource', resourceId], queryFn: ({ signal }) => api.get<Resource>(`/api/v1/resources/${encodeURIComponent(resourceId)}`, undefined, signal), enabled: Boolean(resourceId) }); const { permissions } = useAuth(); const manage = hasPermission(permissions, 'resources.manage')
  return <main className="gf-content"><QueryState query={query}>{(resource) => <><PageHeader title={resource.name} description="Lease ownership and fencing state." /><section className="gf-metric-grid"><div className="gf-metric"><span>State</span><strong><StatusPill status={resourceState(resource)} /></strong></div><div className="gf-metric"><span>Fencing counter</span><strong>{resource.fencingToken ?? 0}</strong></div><div className="gf-metric"><span>Expiry</span><strong><time dateTime={resource.expiresAt}>{formatDateTime(resource.expiresAt)}</time></strong></div></section><section className="gf-card-panel"><h2>Active holder</h2>{resource.holder ? <Link to={`/runs/${resource.holder}`}>{resource.holder}</Link> : <p className="gf-muted">No active lease.</p>}</section>{manage && <div className="gf-dialog-actions"><DangerousAction label="Delete resource" onConfirm={() => api.delete(`/api/v1/resources/${encodeURIComponent(resource.id)}`).then(() => navigate('/resources'))} /></div>}</>}</QueryState></main>
}
